---
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: github.com/kofemann/autoca

stages:
  - test
  - build
  - containerize

format:
  image: golang:latest
  stage: test
  before_script:
    - cd $GOPATH/src
    - mkdir -p $REPO_NAME
    - rmdir $REPO_NAME
    - ln -svf $CI_PROJECT_DIR $REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go mod init
    - go get gopkg.in/yaml.v2
  script:
    - go fmt $(go list ./...)
    - go test -race $(go list ./...)

compile:
  image: golang:latest
  stage: build
  before_script:
    - cd $GOPATH/src
    - mkdir -p $REPO_NAME
    - rmdir $REPO_NAME
    - ln -svf $CI_PROJECT_DIR $REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go mod init
    - go get gopkg.in/yaml.v2
  script:
    - go build -race -ldflags "-extldflags '-static' -X main.revision=`git describe --always --long --dirty`" -o $CI_PROJECT_DIR/autoca
  artifacts:
    paths:
      - autoca


containerize:
  stage: containerize
  image: gcr.io/kaniko-project/executor:debug
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  