---
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: github/kofemann/autoca

stages:
  - test
  - build

format:
  image: golang:latest
  stage: test
  before_script:
    - cd $GOPATH/src
    - mkdir -p $REPO_NAME
    - ln -s $CI_PROJECT_DIR $REPO_NAME
    - go mod init
    - go get gopkg.in/yaml.v2
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  image: golang:latest
  stage: build
  before_script:
    - cd $GOPATH/src
    - mkdir -p $REPO_NAME
    - ln -s $CI_PROJECT_DIR $REPO_NAME
    - go mod init
    - go get gopkg.in/yaml.v2
  script:
    - go build -race -ldflags "-extldflags '-static' -X main.revision=`git describe --always --long --dirty`" -o $CI_PROJECT_DIR/autoca
  artifacts:
    paths:
      - autoca
