---
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: github/kofemann/autoca

stages:
  - test
  - build

format:
  image: golang:latest
  stage: test
  before_script:
    - cd $GOPATH/src
    - mkdir -p $REPO_NAME
    - rmdir $REPO_NAME
    - ln -svf $CI_PROJECT_DIR $REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go mod init
    - go mod tidy
  script:
    - go fmt $(go list ./...)
    - go test -race $(go list ./...)

compile:
  image: golang:latest
  stage: build
  before_script:
    - cd $GOPATH/src
    - mkdir -p $REPO_NAME
    - rmdir $REPO_NAME
    - ln -svf $CI_PROJECT_DIR $REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go mod init
    - go go mod tidy
  script:
    - go build -race -ldflags "-extldflags '-static' -X main.revision=`git describe --always --long --dirty`" -o $CI_PROJECT_DIR/autoca
  artifacts:
    paths:
      - autoca
